### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by AnadeOre** [niloysikdar/Chat-Ly#6]
It'd be nice if the proyect had a good readme with all the documentation and information. It could also have a gif showing the app working. If you assingn it to me I can do it for you 😄 

Example gif:

![Chat gif](https://user-images.githubusercontent.com/71178122/122786446-b477c500-d28a-11eb-86b6-9bbc04fbc5a9.gif)

**Comment by niloysikdar** [comment]
Sure @Uklizdev

**Comment by Uklizdev** [comment]
Done in #9
